name: attendance_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  http: ^1.2.2
  go_router: ^14.2.7
  shared_preferences: ^2.3.2
  flutter_dotenv: ^5.1.0
  syncfusion_flutter_calendar: ^27.1.48

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.12
  custom_lint: ^0.6.5

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/subjectImages/
